
package com.paddez.distro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RmiClinicService", targetNamespace = "http://distro.paddez.com/", wsdlLocation = "http://127.0.0.1:9876/distro?wsdl")
public class RmiClinicService
    extends Service
{

    private final static URL RMICLINICSERVICE_WSDL_LOCATION;
    private final static WebServiceException RMICLINICSERVICE_EXCEPTION;
    private final static QName RMICLINICSERVICE_QNAME = new QName("http://distro.paddez.com/", "RmiClinicService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:9876/distro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RMICLINICSERVICE_WSDL_LOCATION = url;
        RMICLINICSERVICE_EXCEPTION = e;
    }

    public RmiClinicService() {
        super(__getWsdlLocation(), RMICLINICSERVICE_QNAME);
    }

    public RmiClinicService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RMICLINICSERVICE_QNAME, features);
    }

    public RmiClinicService(URL wsdlLocation) {
        super(wsdlLocation, RMICLINICSERVICE_QNAME);
    }

    public RmiClinicService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RMICLINICSERVICE_QNAME, features);
    }

    public RmiClinicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RmiClinicService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RmiClinicInf
     */
    @WebEndpoint(name = "RmiClinicPort")
    public RmiClinicInf getRmiClinicPort() {
        return super.getPort(new QName("http://distro.paddez.com/", "RmiClinicPort"), RmiClinicInf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RmiClinicInf
     */
    @WebEndpoint(name = "RmiClinicPort")
    public RmiClinicInf getRmiClinicPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://distro.paddez.com/", "RmiClinicPort"), RmiClinicInf.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RMICLINICSERVICE_EXCEPTION!= null) {
            throw RMICLINICSERVICE_EXCEPTION;
        }
        return RMICLINICSERVICE_WSDL_LOCATION;
    }

}
