
package Clinic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClinicService", targetNamespace = "http://distro.paddez.com/", wsdlLocation = "http://localhost:9876/distro?wsdl")
public class ClinicService
    extends Service
{

    private final static URL CLINICSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLINICSERVICE_EXCEPTION;
    private final static QName CLINICSERVICE_QNAME = new QName("http://distro.paddez.com/", "ClinicService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/distro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLINICSERVICE_WSDL_LOCATION = url;
        CLINICSERVICE_EXCEPTION = e;
    }

    public ClinicService() {
        super(__getWsdlLocation(), CLINICSERVICE_QNAME);
    }

    public ClinicService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLINICSERVICE_QNAME, features);
    }

    public ClinicService(URL wsdlLocation) {
        super(wsdlLocation, CLINICSERVICE_QNAME);
    }

    public ClinicService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLINICSERVICE_QNAME, features);
    }

    public ClinicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClinicService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Clinic
     */
    @WebEndpoint(name = "ClinicPort")
    public Clinic getClinicPort() {
        return super.getPort(new QName("http://distro.paddez.com/", "ClinicPort"), Clinic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Clinic
     */
    @WebEndpoint(name = "ClinicPort")
    public Clinic getClinicPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://distro.paddez.com/", "ClinicPort"), Clinic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLINICSERVICE_EXCEPTION!= null) {
            throw CLINICSERVICE_EXCEPTION;
        }
        return CLINICSERVICE_WSDL_LOCATION;
    }

}
